spring:
  datasource:
    url: jdbc:postgresql://dpg-ckk98iglk5ic739dcue0-a.oregon-postgres.render.com/srikar_db
    username: dbuser
    password: 7pSYUDRCEsqByV3o4VkxRiZQ960QQgFx
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
